# Question 1

In [3]:
import numpy as np 

arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Qestion 2

In [13]:
import numpy as np
arr1 = []
arr2 = []
for i in range(5):
    i = int(input('Enter 5 element for arr1 : '))
    arr1.append(i)

for i in range(5):
    i = int(input("Enter 5 element for arr2 : "))
    arr2.append(i)

ARR1 = np.array(arr1)
ARR2 = np.array(arr2)
ARR3 = np.concatenate((ARR1,ARR2),axis = None)
print(ARR3)

print(np.sort(ARR3))





Enter 5 element for arr1 : 1
Enter 5 element for arr1 : 2
Enter 5 element for arr1 : 3
Enter 5 element for arr1 : 4
Enter 5 element for arr1 : 5
Enter 5 element for arr2 : 6
Enter 5 element for arr2 : 7
Enter 5 element for arr2 : 8
Enter 5 element for arr2 : 9
Enter 5 element for arr2 : 0
[1 2 3 4 5 6 7 8 9 0]
[0 1 2 3 4 5 6 7 8 9]


# Question 3

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print("Dimension : ",arr.ndim)
print("Size : ",arr.size)

Dimension :  1
Size :  7


# Qustion 4

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr_final = arr.reshape(5, 2)
print(arr_final)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# Question 5

In [11]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print('hstack : ')
print(np.hstack((arr1,arr2)))      
print('\n')
print('vstack : ')
print(np.vstack((arr1,arr2)))


hstack : 
[[1 2 5 6]
 [3 4 7 8]]


vstack : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Question 6

In [16]:
import numpy as np
arr = np.array([1,2,3,4,5,6,1,2,3,4,5,6,9,8,7,2,10,12,34,10,4])
unique_arr,unique_counts = np.unique(arr,return_counts = True)
print('Unique values are : \n',unique_arr,'\n','Unique value count :\n',unique_counts)

Unique values are : 
 [ 1  2  3  4  5  6  7  8  9 10 12 34] 
 Unique value count :
 [2 3 2 3 2 2 1 1 1 2 1 1]
